"""empty message

Revision ID: 6b20f47b6c6c
Revises: b7b897ebee33
Create Date: 2024-06-01 12:56:31.378338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b20f47b6c6c'
down_revision = 'b7b897ebee33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('esterilizado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('esterilizado')

    # ### end Alembic commands ###
