"""empty message

Revision ID: b7b897ebee33
Revises: f6a4ce829917
Create Date: 2024-06-01 12:24:35.262480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b897ebee33'
down_revision = 'f6a4ce829917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('especie',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('cor',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('foto',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('foto',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('descricao',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('cor',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=35),
               existing_nullable=False)
        batch_op.alter_column('especie',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
